name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Set up PHP
      - name: Set up PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring,tokenizer
          tools: composer

      # 3. Cache composer downloads
      - name: Cache composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            ~/.composer/cache/vcs
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # 4. Install PHP dependencies
      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      # 5. Lint with PHP CodeSniffer (abort on any issue)
      - name: Run PHP CodeSniffer
        run: |
          ./vendor/bin/phpcs \
            --standard=PSR2 \
            --runtime-set ignore_warnings_on_exit 0 \
            --extensions=php \
            Structural